#
# We only publish docker files on a push AND if the acafons is the org.
# This way forks don't try to build AND publish
#
name: Publish
on:
  [ push, workflow_dispatch]
jobs:
  publish-image:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [
          "ubuntu-20.04"
        ]
    if: "github.repository_owner == 'acafons'"
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Build the Dockerfiles
        run: make -j $(nproc)
      -
        name: Setup QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ matrix.distro }}.docker
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.distro }}:latest
